// <auto-generated />
using System;
using BackMineros.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackMineros.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240404205453_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackMineros.Models.ControlCamara", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("actualizarImagenReferencia")
                        .HasColumnType("bit");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("pathExe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pathImgReferencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("xmax")
                        .HasColumnType("int");

                    b.Property<int>("xmin")
                        .HasColumnType("int");

                    b.Property<int>("ymax")
                        .HasColumnType("int");

                    b.Property<int>("ymin")
                        .HasColumnType("int");

                    b.Property<int>("zmax")
                        .HasColumnType("int");

                    b.Property<int>("zmin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ControlCamara");
                });

            modelBuilder.Entity("BackMineros.Models.Medicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Volumen")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Mediciones", t =>
                        {
                            t.HasCheckConstraint("CK_Turno", "Turno IN ('Mañana', 'Tarde', 'Noche')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
